language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - DJANGO=django==2.2.7
  - DATABASE_NAME = 'travis_ci_test'
  - DATABASE_USER = 'postgres'
  - DATABASE_PASSWORD = ''

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

# command to install dependencies
install:
    - pip install -r ra/tests/requirements/py3.txt
    - pip install $DJANGO
    - pip install codecov

script:
    - cd tests/
    - coverage run --include=../* runtests.py

after_success:
  - codecov
